/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Entity.Building;
import Entity.ConnectionBuild;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Moshirosang
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Search() throws SQLException {
        initComponents();
        Connection con = ConnectionBuild.getConnection();
        PreparedStatement pstm = con.prepareStatement("SELECT * FROM BUILDING");
        ResultSet rs = pstm.executeQuery();
        while(rs.next()){
            choose.addItem(rs.getString("B_NAME"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choose = new javax.swing.JComboBox<>();
        enter = new javax.swing.JButton();
        back = new javax.swing.JButton();
        twentytwo = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        six = new javax.swing.JButton();
        ten = new javax.swing.JButton();
        eleven = new javax.swing.JButton();
        twentythree = new javax.swing.JButton();
        twentyfour = new javax.swing.JButton();
        twentyfive = new javax.swing.JButton();
        twentysix = new javax.swing.JButton();
        nineteen = new javax.swing.JButton();
        twenty = new javax.swing.JButton();
        twentyseven = new javax.swing.JButton();
        twentyone = new javax.swing.JButton();
        eightteen = new javax.swing.JButton();
        seventeen = new javax.swing.JButton();
        sixteen = new javax.swing.JButton();
        thirtyfive = new javax.swing.JButton();
        thirtyfour = new javax.swing.JButton();
        thirty = new javax.swing.JButton();
        twentynine = new javax.swing.JButton();
        twentyeight = new javax.swing.JButton();
        fifteen = new javax.swing.JButton();
        fourteen = new javax.swing.JButton();
        twelve = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        two = new javax.swing.JButton();
        one = new javax.swing.JButton();
        thirteen = new javax.swing.JButton();
        thirtysix = new javax.swing.JButton();
        thirtythree = new javax.swing.JButton();
        thirtytwo = new javax.swing.JButton();
        thirtyone = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        show = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        getContentPane().add(choose);
        choose.setBounds(930, 30, 320, 30);

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter);
        enter.setBounds(1260, 30, 60, 30);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1190, 500, 130, 60);

        twentytwo.setText("22");
        twentytwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentytwoActionPerformed(evt);
            }
        });
        getContentPane().add(twentytwo);
        twentytwo.setBounds(370, 110, 50, 30);

        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        getContentPane().add(eight);
        eight.setBounds(280, 130, 40, 30);

        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        getContentPane().add(nine);
        nine.setBounds(240, 210, 40, 30);

        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        getContentPane().add(seven);
        seven.setBounds(170, 280, 40, 30);

        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        getContentPane().add(six);
        six.setBounds(160, 340, 40, 30);

        ten.setText("10");
        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });
        getContentPane().add(ten);
        ten.setBounds(250, 270, 50, 30);

        eleven.setText("11");
        eleven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevenActionPerformed(evt);
            }
        });
        getContentPane().add(eleven);
        eleven.setBounds(310, 270, 50, 30);

        twentythree.setText("23");
        twentythree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentythreeActionPerformed(evt);
            }
        });
        getContentPane().add(twentythree);
        twentythree.setBounds(480, 200, 50, 30);

        twentyfour.setText("24");
        twentyfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyfourActionPerformed(evt);
            }
        });
        getContentPane().add(twentyfour);
        twentyfour.setBounds(500, 220, 50, 30);

        twentyfive.setText("25");
        twentyfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyfiveActionPerformed(evt);
            }
        });
        getContentPane().add(twentyfive);
        twentyfive.setBounds(520, 240, 50, 30);

        twentysix.setText("26");
        twentysix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentysixActionPerformed(evt);
            }
        });
        getContentPane().add(twentysix);
        twentysix.setBounds(550, 260, 50, 30);

        nineteen.setText("19");
        nineteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineteenActionPerformed(evt);
            }
        });
        getContentPane().add(nineteen);
        nineteen.setBounds(410, 260, 50, 30);

        twenty.setText("20");
        twenty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyActionPerformed(evt);
            }
        });
        getContentPane().add(twenty);
        twenty.setBounds(450, 280, 50, 30);

        twentyseven.setText("27");
        twentyseven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentysevenActionPerformed(evt);
            }
        });
        getContentPane().add(twentyseven);
        twentyseven.setBounds(500, 290, 50, 30);

        twentyone.setText("21");
        twentyone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyoneActionPerformed(evt);
            }
        });
        getContentPane().add(twentyone);
        twentyone.setBounds(450, 330, 50, 30);

        eightteen.setText("18");
        eightteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightteenActionPerformed(evt);
            }
        });
        getContentPane().add(eightteen);
        eightteen.setBounds(510, 330, 50, 30);

        seventeen.setText("17");
        seventeen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seventeenActionPerformed(evt);
            }
        });
        getContentPane().add(seventeen);
        seventeen.setBounds(480, 360, 50, 30);

        sixteen.setText("16");
        sixteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixteenActionPerformed(evt);
            }
        });
        getContentPane().add(sixteen);
        sixteen.setBounds(500, 390, 50, 30);

        thirtyfive.setText("35");
        thirtyfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyfiveActionPerformed(evt);
            }
        });
        getContentPane().add(thirtyfive);
        thirtyfive.setBounds(570, 320, 50, 30);

        thirtyfour.setText("34");
        thirtyfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyfourActionPerformed(evt);
            }
        });
        getContentPane().add(thirtyfour);
        thirtyfour.setBounds(620, 350, 50, 30);

        thirty.setText("30");
        thirty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyActionPerformed(evt);
            }
        });
        getContentPane().add(thirty);
        thirty.setBounds(580, 400, 50, 30);

        twentynine.setText("29");
        twentynine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentynineActionPerformed(evt);
            }
        });
        getContentPane().add(twentynine);
        twentynine.setBounds(560, 430, 50, 30);

        twentyeight.setText("28");
        twentyeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyeightActionPerformed(evt);
            }
        });
        getContentPane().add(twentyeight);
        twentyeight.setBounds(560, 460, 50, 30);

        fifteen.setText("15");
        fifteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteenActionPerformed(evt);
            }
        });
        getContentPane().add(fifteen);
        fifteen.setBounds(490, 450, 50, 30);

        fourteen.setText("14");
        fourteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourteenActionPerformed(evt);
            }
        });
        getContentPane().add(fourteen);
        fourteen.setBounds(430, 470, 50, 30);

        twelve.setText("12");
        twelve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twelveActionPerformed(evt);
            }
        });
        getContentPane().add(twelve);
        twelve.setBounds(350, 480, 50, 30);

        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        getContentPane().add(three);
        three.setBounds(300, 380, 50, 30);

        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        getContentPane().add(four);
        four.setBounds(220, 410, 40, 30);

        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        getContentPane().add(five);
        five.setBounds(160, 430, 40, 30);

        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        getContentPane().add(two);
        two.setBounds(280, 490, 40, 30);

        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        getContentPane().add(one);
        one.setBounds(290, 523, 40, 30);

        thirteen.setText("13");
        thirteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirteenActionPerformed(evt);
            }
        });
        getContentPane().add(thirteen);
        thirteen.setBounds(320, 560, 50, 30);

        thirtysix.setText("36");
        thirtysix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtysixActionPerformed(evt);
            }
        });
        getContentPane().add(thirtysix);
        thirtysix.setBounds(780, 390, 50, 30);

        thirtythree.setText("33");
        thirtythree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtythreeActionPerformed(evt);
            }
        });
        getContentPane().add(thirtythree);
        thirtythree.setBounds(710, 410, 50, 30);

        thirtytwo.setText("32");
        thirtytwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtytwoActionPerformed(evt);
            }
        });
        getContentPane().add(thirtytwo);
        thirtytwo.setBounds(660, 420, 50, 30);

        thirtyone.setText("31");
        thirtyone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyoneActionPerformed(evt);
            }
        });
        getContentPane().add(thirtyone);
        thirtyone.setBounds(630, 390, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moshirosang\\Desktop\\bangmod-map2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 720);

        show.setColumns(20);
        show.setRows(5);
        jScrollPane1.setViewportView(show);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(930, 80, 390, 380);

        setSize(new java.awt.Dimension(2252, 1746));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed

    }//GEN-LAST:event_chooseActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Homepage home = new Homepage();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void twentytwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentytwoActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(22).toString());
    }//GEN-LAST:event_twentytwoActionPerformed

    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(10).toString());
    }//GEN-LAST:event_tenActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(6).toString());
    }//GEN-LAST:event_sixActionPerformed

    private void thirtyfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyfiveActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(35).toString());
    }//GEN-LAST:event_thirtyfiveActionPerformed

    private void twentysevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentysevenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(27).toString());

    }//GEN-LAST:event_twentysevenActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(1).toString());
    }//GEN-LAST:event_oneActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(5).toString());
    }//GEN-LAST:event_fiveActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(8).toString());
    }//GEN-LAST:event_eightActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(2).toString());
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(3).toString());
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(4).toString());
    }//GEN-LAST:event_fourActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(7).toString());
    }//GEN-LAST:event_sevenActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(9).toString());
    }//GEN-LAST:event_nineActionPerformed

    private void elevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(11).toString());
    }//GEN-LAST:event_elevenActionPerformed

    private void twelveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twelveActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(12).toString());
    }//GEN-LAST:event_twelveActionPerformed

    private void thirteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirteenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(13).toString());
    }//GEN-LAST:event_thirteenActionPerformed

    private void fourteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourteenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(14).toString());
    }//GEN-LAST:event_fourteenActionPerformed

    private void fifteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(15).toString());
    }//GEN-LAST:event_fifteenActionPerformed

    private void sixteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixteenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(16).toString());
    }//GEN-LAST:event_sixteenActionPerformed

    private void seventeenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seventeenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(17).toString());
    }//GEN-LAST:event_seventeenActionPerformed

    private void eightteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightteenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(18).toString());
    }//GEN-LAST:event_eightteenActionPerformed

    private void nineteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineteenActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(19).toString());
    }//GEN-LAST:event_nineteenActionPerformed

    private void twentyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(20).toString());
    }//GEN-LAST:event_twentyActionPerformed

    private void twentyoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyoneActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(21).toString());
    }//GEN-LAST:event_twentyoneActionPerformed

    private void twentythreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentythreeActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(23).toString());
    }//GEN-LAST:event_twentythreeActionPerformed

    private void twentyfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyfourActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(24).toString());
    }//GEN-LAST:event_twentyfourActionPerformed

    private void twentyfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyfiveActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(25).toString());
    }//GEN-LAST:event_twentyfiveActionPerformed

    private void twentysixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentysixActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(26).toString());
    }//GEN-LAST:event_twentysixActionPerformed

    private void twentyeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyeightActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(28).toString());
    }//GEN-LAST:event_twentyeightActionPerformed

    private void twentynineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentynineActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(29).toString());
    }//GEN-LAST:event_twentynineActionPerformed

    private void thirtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(30).toString());
    }//GEN-LAST:event_thirtyActionPerformed

    private void thirtyoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyoneActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(31).toString());
    }//GEN-LAST:event_thirtyoneActionPerformed

    private void thirtytwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtytwoActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(32).toString());
    }//GEN-LAST:event_thirtytwoActionPerformed

    private void thirtythreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtythreeActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(33).toString());
    }//GEN-LAST:event_thirtythreeActionPerformed

    private void thirtyfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyfourActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(34).toString());
    }//GEN-LAST:event_thirtyfourActionPerformed

    private void thirtysixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtysixActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(36).toString());
    }//GEN-LAST:event_thirtysixActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        String name = choose.getSelectedItem().toString();
        String detail = Building.showDetailBuild(name).toString();
        Building.showDetailBuild(name).getBuildingID();//ยังไม่เสร็จ
        show.setText(detail);
    }//GEN-LAST:event_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Search().setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> choose;
    private javax.swing.JButton eight;
    private javax.swing.JButton eightteen;
    private javax.swing.JButton eleven;
    private javax.swing.JButton enter;
    private javax.swing.JButton fifteen;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton fourteen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nine;
    private javax.swing.JButton nineteen;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton seventeen;
    private javax.swing.JTextArea show;
    private javax.swing.JButton six;
    private javax.swing.JButton sixteen;
    private javax.swing.JButton ten;
    private javax.swing.JButton thirteen;
    private javax.swing.JButton thirty;
    private javax.swing.JButton thirtyfive;
    private javax.swing.JButton thirtyfour;
    private javax.swing.JButton thirtyone;
    private javax.swing.JButton thirtysix;
    private javax.swing.JButton thirtythree;
    private javax.swing.JButton thirtytwo;
    private javax.swing.JButton three;
    private javax.swing.JButton twelve;
    private javax.swing.JButton twenty;
    private javax.swing.JButton twentyeight;
    private javax.swing.JButton twentyfive;
    private javax.swing.JButton twentyfour;
    private javax.swing.JButton twentynine;
    private javax.swing.JButton twentyone;
    private javax.swing.JButton twentyseven;
    private javax.swing.JButton twentysix;
    private javax.swing.JButton twentythree;
    private javax.swing.JButton twentytwo;
    private javax.swing.JButton two;
    // End of variables declaration//GEN-END:variables

