package project;

import Entity.Building;
import Entity.ConnectionBuild;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Moshirosang
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Search() throws SQLException {
        initComponents();
        Connection con = ConnectionBuild.getConnection();
        PreparedStatement pstm = con.prepareStatement("SELECT * FROM BUILDING");
        ResultSet rs = pstm.executeQuery();
        while(rs.next()){
            choose.addItem(rs.getString("B_NAME"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choose = new javax.swing.JComboBox<>();
        enter = new javax.swing.JButton();
        back = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b36 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        show = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        getContentPane().add(choose);
        choose.setBounds(930, 30, 320, 30);

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter);
        enter.setBounds(1260, 30, 60, 30);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1190, 500, 130, 60);

        b22.setText("22");
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        getContentPane().add(b22);
        b22.setBounds(370, 110, 50, 30);

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(280, 130, 40, 30);

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(240, 210, 40, 30);

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(170, 280, 40, 30);

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(160, 340, 40, 30);

        b10.setText("10");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10);
        b10.setBounds(250, 270, 50, 30);

        b11.setText("11");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        getContentPane().add(b11);
        b11.setBounds(310, 270, 50, 30);

        b23.setText("23");
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });
        getContentPane().add(b23);
        b23.setBounds(480, 200, 50, 30);

        b24.setText("24");
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });
        getContentPane().add(b24);
        b24.setBounds(500, 220, 50, 30);

        b25.setText("25");
        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });
        getContentPane().add(b25);
        b25.setBounds(520, 240, 50, 30);

        b26.setText("26");
        b26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b26ActionPerformed(evt);
            }
        });
        getContentPane().add(b26);
        b26.setBounds(550, 260, 50, 30);

        b19.setText("19");
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });
        getContentPane().add(b19);
        b19.setBounds(410, 260, 50, 30);

        b20.setText("20");
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });
        getContentPane().add(b20);
        b20.setBounds(450, 280, 50, 30);

        b27.setText("27");
        b27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b27ActionPerformed(evt);
            }
        });
        getContentPane().add(b27);
        b27.setBounds(500, 290, 50, 30);

        b21.setText("21");
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        getContentPane().add(b21);
        b21.setBounds(450, 330, 50, 30);

        b18.setText("18");
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });
        getContentPane().add(b18);
        b18.setBounds(510, 330, 50, 30);

        b17.setText("17");
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });
        getContentPane().add(b17);
        b17.setBounds(480, 360, 50, 30);

        b16.setText("16");
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        getContentPane().add(b16);
        b16.setBounds(500, 390, 50, 30);

        b35.setText("35");
        b35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b35ActionPerformed(evt);
            }
        });
        getContentPane().add(b35);
        b35.setBounds(570, 320, 50, 30);

        b34.setText("34");
        b34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b34ActionPerformed(evt);
            }
        });
        getContentPane().add(b34);
        b34.setBounds(620, 350, 50, 30);

        b30.setText("30");
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });
        getContentPane().add(b30);
        b30.setBounds(580, 400, 50, 30);

        b29.setText("29");
        b29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b29ActionPerformed(evt);
            }
        });
        getContentPane().add(b29);
        b29.setBounds(560, 430, 50, 30);

        b28.setText("28");
        b28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b28ActionPerformed(evt);
            }
        });
        getContentPane().add(b28);
        b28.setBounds(560, 460, 50, 30);

        b15.setText("15");
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        getContentPane().add(b15);
        b15.setBounds(490, 450, 50, 30);

        b14.setText("14");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        getContentPane().add(b14);
        b14.setBounds(430, 470, 50, 30);

        b12.setText("12");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        getContentPane().add(b12);
        b12.setBounds(350, 480, 50, 30);

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(300, 380, 50, 30);

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(220, 410, 40, 30);

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(160, 430, 40, 30);

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(280, 490, 40, 30);

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(290, 523, 40, 30);

        b13.setText("13");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        getContentPane().add(b13);
        b13.setBounds(320, 560, 50, 30);

        b36.setText("36");
        b36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b36ActionPerformed(evt);
            }
        });
        getContentPane().add(b36);
        b36.setBounds(780, 390, 50, 30);

        b33.setText("33");
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });
        getContentPane().add(b33);
        b33.setBounds(710, 410, 50, 30);

        b32.setText("32");
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });
        getContentPane().add(b32);
        b32.setBounds(660, 420, 50, 30);

        b31.setText("31");
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });
        getContentPane().add(b31);
        b31.setBounds(630, 390, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Moshirosang\\Desktop\\bangmod-map2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 720);

        show.setColumns(20);
        show.setRows(5);
        jScrollPane1.setViewportView(show);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(930, 80, 390, 380);

        setSize(new java.awt.Dimension(2252, 1746));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed

    }//GEN-LAST:event_chooseActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Homepage home = new Homepage();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(22).toString());
        setBgColor();
        b22.setBackground(Color.red);
    }//GEN-LAST:event_b22ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(10).toString());
        setBgColor();
        b10.setBackground(Color.red);
    }//GEN-LAST:event_b10ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(6).toString());
        setBgColor();
        b6.setBackground(Color.red);
    }//GEN-LAST:event_b6ActionPerformed

    private void b35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b35ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(35).toString());
        setBgColor();
        b35.setBackground(Color.red);
    }//GEN-LAST:event_b35ActionPerformed

    private void b27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b27ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(27).toString());
        setBgColor();
        b27.setBackground(Color.red);
    }//GEN-LAST:event_b27ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(1).toString());
        setBgColor();
        b1.setBackground(Color.red);
    }//GEN-LAST:event_b1ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(5).toString());
        setBgColor();
        b5.setBackground(Color.red);
    }//GEN-LAST:event_b5ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(8).toString());
        setBgColor();
        b8.setBackground(Color.red);
    }//GEN-LAST:event_b8ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(2).toString());
        setBgColor();
        b2.setBackground(Color.red);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(3).toString());
        setBgColor();
        b3.setBackground(Color.red);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(4).toString());
        setBgColor();
        b4.setBackground(Color.red);
    }//GEN-LAST:event_b4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(7).toString());
        setBgColor();
        b7.setBackground(Color.red);
    }//GEN-LAST:event_b7ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(9).toString());
        setBgColor();
        b9.setBackground(Color.red);
    }//GEN-LAST:event_b9ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(11).toString());
        setBgColor();
        b11.setBackground(Color.red);
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(12).toString());
        setBgColor();
        b12.setBackground(Color.red);        
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(13).toString());
        setBgColor();
        b13.setBackground(Color.red);
    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(14).toString());
        setBgColor();
        b14.setBackground(Color.red);
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(15).toString());
        setBgColor();
        b15.setBackground(Color.red);
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(16).toString());
        setBgColor();
        b16.setBackground(Color.red);
    }//GEN-LAST:event_b16ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(17).toString());
        setBgColor();
        b17.setBackground(Color.red);
    }//GEN-LAST:event_b17ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(18).toString());
        setBgColor();
        b18.setBackground(Color.red);
    }//GEN-LAST:event_b18ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(19).toString());
        setBgColor();
        b19.setBackground(Color.red);
    }//GEN-LAST:event_b19ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(20).toString());
        setBgColor();
        b20.setBackground(Color.red);
    }//GEN-LAST:event_b20ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(21).toString());
        setBgColor();
        b21.setBackground(Color.red);
    }//GEN-LAST:event_b21ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(23).toString());
        setBgColor();
        b23.setBackground(Color.red);
    }//GEN-LAST:event_b23ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(24).toString());
        setBgColor();
        b24.setBackground(Color.red);
    }//GEN-LAST:event_b24ActionPerformed

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(25).toString());
        setBgColor();
        b25.setBackground(Color.red);
    }//GEN-LAST:event_b25ActionPerformed

    private void b26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b26ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(26).toString());
        setBgColor();
        b26.setBackground(Color.red);
    }//GEN-LAST:event_b26ActionPerformed

    private void b28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b28ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(28).toString());
        setBgColor();
        b28.setBackground(Color.red);
    }//GEN-LAST:event_b28ActionPerformed

    private void b29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b29ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(29).toString());
        setBgColor();
        b29.setBackground(Color.red);
    }//GEN-LAST:event_b29ActionPerformed

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(30).toString());
        setBgColor();
        b30.setBackground(Color.red);
    }//GEN-LAST:event_b30ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(31).toString());
        setBgColor();
        b31.setBackground(Color.red);
    }//GEN-LAST:event_b31ActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(32).toString());
        setBgColor();
        b32.setBackground(Color.red);
    }//GEN-LAST:event_b32ActionPerformed

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(33).toString());
        setBgColor();
        b33.setBackground(Color.red);
    }//GEN-LAST:event_b33ActionPerformed

    private void b34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b34ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(34).toString());
        setBgColor();
        b34.setBackground(Color.red);
    }//GEN-LAST:event_b34ActionPerformed

    private void b36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b36ActionPerformed
        // TODO add your handling code here:
        show.setText(Building.showDetailBuild(36).toString());
        setBgColor();
        b36.setBackground(Color.red);
    }//GEN-LAST:event_b36ActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        String name = choose.getSelectedItem().toString();
        String detail = Building.showDetailBuild(name).toString();
        setBgColor();
        switch(Building.showDetailBuild(name).getBuildingID()){
            case 1 : b1.setBackground(Color.red); break;
            case 2 : b2.setBackground(Color.red);break;
            case 3 : b3.setBackground(Color.red);break;
            case 4 : b4.setBackground(Color.red);break;
            case 5 : b5.setBackground(Color.red);break;
            case 6 : b6.setBackground(Color.red);break;
            case 7 : b7.setBackground(Color.red);break;
            case 8 : b8.setBackground(Color.red);break;
            case 9 : b9.setBackground(Color.red);break;
            case 10 : b10.setBackground(Color.red);break;
            case 11 : b11.setBackground(Color.red);break;
            case 12 : b12.setBackground(Color.red);break;
            case 13 : b13.setBackground(Color.red);break;
            case 14 : b14.setBackground(Color.red);break;
            case 15 : b15.setBackground(Color.red);break;
            case 16 : b16.setBackground(Color.red);break;
            case 17 : b17.setBackground(Color.red);break;
            case 18 : b18.setBackground(Color.red);break;
            case 19 : b19.setBackground(Color.red);break;
            case 20 : b20.setBackground(Color.red);break;
            case 21 : b21.setBackground(Color.red);break;
            case 22 : b22.setBackground(Color.red);break;
            case 23 : b23.setBackground(Color.red);break;
            case 24 : b24.setBackground(Color.red);break;
            case 25 : b25.setBackground(Color.red);break;
            case 26 : b26.setBackground(Color.red);break;
            case 27 : b27.setBackground(Color.red);break;
            case 28 : b28.setBackground(Color.red);break;
            case 29 : b29.setBackground(Color.red);break;
            case 30 : b30.setBackground(Color.red);break;
            case 31 : b31.setBackground(Color.red);break;
            case 32 : b32.setBackground(Color.red);break;
            case 33 : b32.setBackground(Color.red);break;
            case 34 : b32.setBackground(Color.red);break;
            case 35 : b32.setBackground(Color.red);break;
            case 36 : b32.setBackground(Color.red);break;
        }
        show.setText(detail);
    }//GEN-LAST:event_enterActionPerformed
    public void setBgColor(){
        b1.setBackground(Color.lightGray);
        b2.setBackground(Color.lightGray);
        b3.setBackground(Color.lightGray);
        b4.setBackground(Color.lightGray);
        b5.setBackground(Color.lightGray);
        b6.setBackground(Color.lightGray);
        b7.setBackground(Color.lightGray);
        b8.setBackground(Color.lightGray);
        b9.setBackground(Color.lightGray);
        b10.setBackground(Color.lightGray);
        b11.setBackground(Color.lightGray);
        b12.setBackground(Color.lightGray);
        b13.setBackground(Color.lightGray);
        b14.setBackground(Color.lightGray);
        b15.setBackground(Color.lightGray);
        b16.setBackground(Color.lightGray);
        b17.setBackground(Color.lightGray);
        b18.setBackground(Color.lightGray);
        b19.setBackground(Color.lightGray);
        b20.setBackground(Color.lightGray);
        b21.setBackground(Color.lightGray);
        b22.setBackground(Color.lightGray);
        b23.setBackground(Color.lightGray);
        b24.setBackground(Color.lightGray);
        b25.setBackground(Color.lightGray);
        b26.setBackground(Color.lightGray);
        b27.setBackground(Color.lightGray);
        b28.setBackground(Color.lightGray);
        b29.setBackground(Color.lightGray);
        b30.setBackground(Color.lightGray);
        b31.setBackground(Color.lightGray);
        b32.setBackground(Color.lightGray);
        b33.setBackground(Color.lightGray);
        b34.setBackground(Color.lightGray);
        b35.setBackground(Color.lightGray);
        b36.setBackground(Color.lightGray);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Search().setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b29;
    private javax.swing.JButton b3;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b35;
    private javax.swing.JButton b36;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> choose;
    private javax.swing.JButton enter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea show;
    // End of variables declaration//GEN-END:variables
}
